### ISSUE TITLE
Removing 'All Good!' validation text and all exclamation points removed from alert text

### ISSUE THREAD

**Issue by cdnovack** [jjprogramsllc/practical-form.js#44]
When practical-form fields pass validation, they display a message reading 'All Good!'. I request that this message be removed entirely as it is unnecessary (messages that appear on validation failure can remain). 

Additionally, if possible, where there is alert text displayed to the user in the code, I would like to request that exclamation points are removed from the text (can be replaced with a period or left without punctuation).

**Comment by joewashear007** [comment]
Thanks. This is related to #42. I will add a config option to both change the text and to turn off the messages.

**Comment by joewashear007** [comment]
Closed in Version 3.0.0
